# Generated by Django 5.1.4 on 2026-07-05 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('lab', 'Lab')], default='lab', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('hematology', 'Hematology'), ('chemistry', 'Chemistry'), ('microbiology', 'Microbiology'), ('immunology', 'Immunology'), ('molecular', 'Molecular'), ('pathology', 'Pathology')], max_length=20)),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('saliva', 'Saliva'), ('swab', 'Swab'), ('stool', 'Stool'), ('tissue', 'Tissue'), ('other', 'Other')], default='blood', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('prep_instructions', models.TextField(blank=True)),
                ('turnaround_hours', models.PositiveIntegerField(default=24)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestAnalyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytes', to='directory.labtest')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('lab_test', 'name'), name='unique_analyte_per_test')],
            },
        ),
    ]
